# Pristine Portfolio Tool - Cloudflare Configuration

name = "pristine-portfolio"
main = "./worker/index.js"
compatibility_date = "2024-01-01"

# Environment Variables
[env.production.vars]
ENVIRONMENT = "production"
OPENAI_API_KEY = "" # Add your OpenAI API key here
ALLOWED_ORIGINS = "https://app.planpulse.us,https://planpulse.us"

[env.staging.vars]
ENVIRONMENT = "staging"  
OPENAI_API_KEY = "" # Add your OpenAI API key here
ALLOWED_ORIGINS = "https://staging.planpulse.us"

# Database Bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "pristine-portfolio-db"
database_id = "" # Add your D1 database ID here

[[env.staging.d1_databases]]
binding = "DB" 
database_name = "pristine-portfolio-staging"
database_id = "" # Add staging database ID here

# KV Bindings for caching
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "" # Will be created during setup

# Routes
[env.production]
routes = [
  { pattern = "api.planpulse.us/*", zone_name = "planpulse.us" }
]

[env.staging]
routes = [
  { pattern = "api-staging.planpulse.us/*", zone_name = "planpulse.us" }
]

# Build configuration
[build]
command = "echo 'No build needed for static frontend'"

# Analytics and monitoring
[observability]
enabled = true